### ISSUE TITLE
Can't run gtest after #103

### ISSUE THREAD

**Issue by YoungSeokHong** [euphony-io/euphony#109]
![image](https://user-images.githubusercontent.com/80624082/136691371-1ff5c14e-8862-4e15-8d3d-3778f0e007d8.png)

After I pulled project I couldn't run gtest with error below😢
```error
CMake Error at C:/Users/YoungHong/euphony/euphony/src/main/cpp/tests/cmake.run.test.script:7 (string):
string sub-command STRIP requires two arguments.
```

I'm sorry that I find it too late, but can I ask why did you put string command to outside? @kuro11pow2 

![image](https://user-images.githubusercontent.com/80624082/136691506-e98c003a-9200-4c0a-a525-80a4e5f159f6.png)

**Comment by kuro11pow2** [comment]
OUTPUT should always be printed regardless of GTEST_RESULT, so it was processed outside the conditional statement.
In my case, the right test case, the wrong test case, both cases were built well. In addition, it seems that two factors of STRIP are given. Can you tell us what kind of environment it is?

# Wrong test case
![image](https://user-images.githubusercontent.com/47289893/136691845-88936a43-e0aa-4279-ab8f-183c6cacefc8.png)

@ Right test case
![image](https://user-images.githubusercontent.com/47289893/136691856-873e9a97-ba95-429b-aec0-74968856aa73.png)

**Comment by YoungSeokHong** [comment]
> OUTPUT should always be printed regardless of GTEST_RESULT, so it was processed outside the conditional statement.
I see!

I don't know why but the error occur when I push more than 3 cases in base64Test.cpp😢 Do you have any idea?
![image](https://user-images.githubusercontent.com/80624082/136693063-e069ed7f-69ac-4f44-9bc8-611b4f9aa4bf.png)
![image](https://user-images.githubusercontent.com/80624082/136693066-82fe8c42-d99f-4a42-8e28-cd6b9993836f.png)

**Comment by yeonns** [comment]
@YoungSeokHong Maybe it is related to https://github.com/euphony-io/euphony/discussions/63!
API 28 + number of gtest issue. What is your device API version?

**Comment by YoungSeokHong** [comment]
> @YoungSeokHong Maybe it is related to #63! API 28 + number of gtest issue. What is your device API version?

Oh! You are right! I get fail at API level 28, but success at API level 30.
My device API version was level 28 before.
Thank you!😀

**Comment by yeonns** [comment]
@designe https://github.com/euphony-io/euphony/issues/116
we need solution other than warning messages. 😭
