### ISSUE TITLE
Support Issues Template for `feature request`

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#137]
This is one of the `good first issue`

This repository has the old `feature request` template that has made by `markdown`
https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

We have plan to update modern issue templates that have customizable web form fields.
One of the great example is our `bug report` [here](https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml), [PR link](https://github.com/euphony-io/euphony/pull/130)

In this issue, we need to make `feature request`'s issue template

### Requirement
- Improve current legacy [feature request](https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/feature_request.md). Feel free to modify & append more questions
- Use yaml : please read here [syntax for githubs for schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema), [Learn YAML in Y minutes](https://learnxinyminutes.com/docs/yaml/)
- Refer to below references.

### References
- next.js : https://github.com/vercel/next.js/tree/canary/.github/ISSUE_TEMPLATE
- Angular : https://github.com/angular/angular/blob/main/.github/ISSUE_TEMPLATE
- monaco-editor : https://github.com/microsoft/monaco-editor/tree/main/.github/ISSUE_TEMPLATE
- pytorch : https://github.com/pytorch/pytorch/tree/master/.github/ISSUE_TEMPLATE

**Comment by defwdahyun0** [comment]
@euphony-io/waveup Our team wants to solve this issue!

**Comment by sunyeongan** [comment]
---
 name: Feature request
 about: Suggest an idea for this project
 title: ''
 labels: ''
 assignees: ''

---
 body:
  - type: markdown
    attributes:
      value: Is your feature request related to a problem? Please describe.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description : A clear and concise description of what the problem is. Ex.  I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
     validations:
       required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions  or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add2 any other context or screenshots about the feature       request here.
    validations:
      required: true

**Comment by defwdahyun0** [comment]
I usually like to check directly on github.
I checked your code directly on my github. You can check the link below.

https://github.com/defwdahyun0/issue-template-tutorial/blob/main/.github/ISSUE_TEMPLATE/feature_request.yaml

I confirmed that you posted a question on discusion about how to check the yaml file on the web. Sounds like a good question. When the answer comes up, I also want to check and get a tip.

**Comment by defwdahyun0** [comment]
Our assignment includes the following questions.

"Improve current legacy feature request. Feel free to modify & append more questions"

What else should we add to the feature request issue template? I want to discuss freely on the issue page.

**Comment by Han-D-Peter** [comment]
Euphony.js is built from 4 programming language C++, java, javascript, kotlin. I think it would be good to have 4 related questions asked.
