### ISSUE TITLE
Support Issues Template for `sample app proposal`

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#138]
This is one of the `good first issue`

This repository doesn't have the `Sample App Proposal`
We have plan to create modern issue templates that have customizable web form fields.
One of the great example is our `bug report` [here](https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml), [PR link](https://github.com/euphony-io/euphony/pull/130)
In this issue, we need to make `Sample App Proposal`'s issue template

### Requirement
- title field [required]
- description field [required]
- contributors field [required] (who made it?)
- repository link [required]
- Feel free to append more field.
- Use yaml : please read here [syntax for githubs for schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema), [Learn YAML in Y minutes](https://learnxinyminutes.com/docs/yaml/)
- Refer to below references.

### References
- next.js : https://github.com/vercel/next.js/tree/canary/.github/ISSUE_TEMPLATE
- Angular : https://github.com/angular/angular/blob/main/.github/ISSUE_TEMPLATE
- monaco-editor : https://github.com/microsoft/monaco-editor/tree/main/.github/ISSUE_TEMPLATE
- pytorch : https://github.com/pytorch/pytorch/tree/master/.github/ISSUE_TEMPLATE

**Comment by serim53** [comment]
Our team wanna resolve this issue!☺️

**Comment by SeonJK** [comment]
I am sorry that I clicked 'unassignme' button by mistake...

Could you assgin me again...?

**Comment by SeonJK** [comment]
Here is form elements I wrote. Please any comments about this!

Before start, I am summarizing YAML documents in Korean.
Here is my notion link with edit permission. Please come and edit together!!
https://www.notion.so/seonjk/YAML-8ae1a967ebab4d47bcdb09a4fc1acc88 


- title field [required]
- [ ] type: input
- [ ] id: app_name
- [ ] attributes/label: What's your app name?
- [ ] attributes/description: 
- [ ] validations/required: true

- description field [required]
- [ ] type: textarea
- [ ] id: description
- [ ] attributes/lable: Description
- [ ] validations/required: true

- contributors field [required] (who made it?)
- TODO: I have no idea,,,

- repository link [required]
- [ ] type: input
- [ ] id: repository_link
- [ ] attributes/label: Submit your repository link!
- [ ] attributes/description: "Please submit your sample app repository"
- [ ] attributes/placeholder: "Example: github.com/euphony-io/your-sample-app"
- [ ] attributes/value: "github.com/euphony-io/"
- [ ] validations/required: true

**Comment by serim53** [comment]
> Here is form elements I wrote. Please any comments about this!
> 
> Before start, I am summarizing YAML documents in Korean. Here is my notion link with edit permission. Please come and edit together!! https://www.notion.so/seonjk/YAML-8ae1a967ebab4d47bcdb09a4fc1acc88
> 
> * title field [required]
> * [ ]  type: input
> * [ ]  id: app_name
> * [ ]  attributes/label: What's your app name?
> * [ ]  attributes/description:
> * [ ]  validations/required: true
> * description field [required]
> * [ ]  type: textarea
> * [ ]  id: description
> * [ ]  attributes/lable: Description
> * [ ]  validations/required: true
> * contributors field [required] (who made it?)
> * TODO: I have no idea,,,
> * repository link [required]
> * [ ]  type: input
> * [ ]  id: repository_link
> * [ ]  attributes/label: Submit your repository link!
> * [ ]  attributes/description: "Please submit your sample app repository"
> * [ ]  attributes/placeholder: "Example: github.com/euphony-io/your-sample-app"
> * [ ]  attributes/value: "github.com/euphony-io/"
> * [ ]  validations/required: true

Thank you for posting! But it says I don't have access permission on the Notion page...!

**Comment by SeonJK** [comment]
> > Here is form elements I wrote. Please any comments about this!
> > Before start, I am summarizing YAML documents in Korean. Here is my notion link with edit permission. Please come and edit together!! https://www.notion.so/seonjk/YAML-8ae1a967ebab4d47bcdb09a4fc1acc88
> > 
> > * title field [required]
> > * [ ]   type: input
> > * [ ]   id: app_name
> > * [ ]   attributes/label: What's your app name?
> > * [ ]   attributes/description:
> > * [ ]   validations/required: true
> > * description field [required]
> > * [ ]   type: textarea
> > * [ ]   id: description
> > * [ ]   attributes/lable: Description
> > * [ ]   validations/required: true
> > * contributors field [required] (who made it?)
> > * TODO: I have no idea,,,
> > * repository link [required]
> > * [ ]   type: input
> > * [ ]   id: repository_link
> > * [ ]   attributes/label: Submit your repository link!
> > * [ ]   attributes/description: "Please submit your sample app repository"
> > * [ ]   attributes/placeholder: "Example: github.com/euphony-io/your-sample-app"
> > * [ ]   attributes/value: "github.com/euphony-io/"
> > * [ ]   validations/required: true
> 
> Thank you for posting! But it says I don't have access permission on the Notion page...!

I update another link. Would you try to access this link?

**Comment by phj0407** [comment]
Yse. I can access well.

**Comment by serim53** [comment]
Thank you for your quick feedback! I'll study and add the necessary parts!

**Comment by phj0407** [comment]
In contributor's field, How about add

type: textarea
attributes/label: Who made it?
attributes/description: Write conrtibutors ID with profile link
validations / required: true

**Comment by SeonJK** [comment]
@phj0407 Good opinion!! 
How about write `placeholder` also?
is it correct your description means "SeonJK https://github.com/SeonJK"?

**Comment by phj0407** [comment]
Yes, that's right. Writing placeholder is also good idea! How about add

attributes/placeholder: "Example: SeonJK  ::  https://github.com/SeonJK" ?

**Comment by SeonJK** [comment]
OK. I will apply your feedback!!

**Comment by designe** [comment]
We have used only pull request last year.

I'm sharing some PR examples
- https://github.com/euphony-io/euphony/pull/36
- https://github.com/euphony-io/euphony/pull/113
- https://github.com/euphony-io/euphony/pull/117

**Comment by SeonJK** [comment]
Reading past PRs, I suggest to update some keys

- I think "The features of the app are as follows:" will be good for `label` of description field instead of "Description".
- I want to add some texts in `placeholder` of contributors like "Example: Co-Authored-By: username :: https://github.com/username" and add `value` key : "Co-Authored-By: "

please any comments about suggestions. Thanks!

**Comment by phj0407** [comment]
Both ideas are so good! I think we can apply it right away👍👍

**Comment by SeonJK** [comment]
@serim53 is it okay about my suggestion? Then I will pull first request!

**Comment by serim53** [comment]
I'm sorry for the late feedback😥..
 I think all of your opinions are good! And I agree with everything to add!

My Additional suggestions are:
1. How about creating a field for Feature?
2. Why don't we create a field for additional content so that we can attach screenshots and provide additional explanations?

**Comment by phj0407** [comment]
You mean adding [Feature] , [Screenshot] section? I think adding  [Screenshot] separately is good idea!

And,... users will write brief feature of app in [Feature] and more details in [description] ? Am i right to understand?

**Comment by SeonJK** [comment]
@serim53 @phj0407 Thank u for good opinion!!
I think it's good to be placed in [Description] field with Screenshot and description. With description, it's more helpful to understand I think :)

About your opinions, [Feature] field would be helpful to describe brief features!!

**Comment by serim53** [comment]
@phj0407 @SeonJK I agree with both of your opinion! Then, shall we add only the feature field, and an additional explanation to the description? 😄

**Comment by SeonJK** [comment]
Great!! Do you have any idea about explanation about description?

**Comment by phj0407** [comment]
I think it's enough for now. It will be great template for sample app proposal 👍 I'll tell you when I have a good idea.

**Comment by SeonJK** [comment]
> Here is form elements I wrote. Please any comments about this!
> 
> Before start, I am summarizing YAML documents in Korean. Here is my notion link with edit permission. Please come and edit together!! https://seonjk.notion.site/YAML-8ae1a967ebab4d47bcdb09a4fc1acc88
> 
> * title field [required]
> * [ ]  type: input
> * [ ]  id: app_title
> * [ ]  attributes/label: "What's your app name?"
> * [ ]  validations/required: true
> * feature field [required]
> * [ ]  type: textarea
> * [ ]  id: feature
> * [ ]  attributes/label: "The feature of app are..."
> * [ ]  attributes/description: "Summarize the feature of your app"
> * [ ]  attributes/value: 3-lines of list
> * description field [required]
> * [ ]  type: textarea
> * [ ]  id: description
> * [ ]  attributes/label: "The features of the app are as follows:"
> * [ ]  attributes/description: "Describe how your app works! you can also use snapshots of your app."
> * [ ]  validations/required: true
> * contributors field [required] (who made it?)
> * [ ]  type: textarea
> * [ ]  attributes/label: Who made it?
> * [ ]  attributes/description: "Write contributors ID with profile link"
> * [ ]  attributes/placeholder: "Example: Co-Authored-By: username :: https://github.com/username"
> * [ ]  attributes/value: "Co-Authored-By: "
> * repository link [required]
> * [ ]  type: input
> * [ ]  id: repository_link
> * [ ]  attributes/label: Submit your repository link!
> * [ ]  attributes/description: "Please submit your sample app repository"
> * [ ]  attributes/placeholder: "Example: https://github.com/euphony-io/your-sample-app"
> * [ ]  attributes/value: "https://github.com/euphony-io/"
> * [ ]  validations/required: true

Alright! I updated our opinions and wrote my idea of feature field.
