### ISSUE TITLE
Support Issues Template for `documentation`

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#139]
This is one of the `good first issue`

There is no `Documentation` issue template in this repository.
We have plan to create modern issue templates that have customizable web form fields.
One of the great example is our `bug report` [here](https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml), [PR link](https://github.com/euphony-io/euphony/pull/130)
In this issue, we need to make `Documentation`'s issue template

### Requirement
- Title [required]
- Does the documents page already exists? Please link to it [optional]
- What is the issue of docs? [required]
- Suggest a potential alternative/fix [required]
- Feel free to append more field.
- Use yaml : please read here [syntax for githubs for schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema), [Learn YAML in Y minutes](https://learnxinyminutes.com/docs/yaml/)
- Refer to below references.

### References
- next.js : https://github.com/vercel/next.js/tree/canary/.github/ISSUE_TEMPLATE
- Angular : https://github.com/angular/angular/blob/main/.github/ISSUE_TEMPLATE
- monaco-editor : https://github.com/microsoft/monaco-editor/tree/main/.github/ISSUE_TEMPLATE
- pytorch : https://github.com/pytorch/pytorch/tree/master/.github/ISSUE_TEMPLATE

**Comment by hyunjung-choi** [comment]
@euphony-io/soundary
We want this issue!

**Comment by chaso1495** [comment]
I think we can process this issue enough with a few hour and links, let's meet at even and study about this issue together.
@hyunjung-choi  @JoHyoju04
