### ISSUE TITLE
Clean up & Remove legacy stuff (like .idea folder)

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#159]
This is one of the `good first issue`

In `euphony` repository, there is a `.gitignore`
https://github.com/euphony-io/euphony/blob/40b13311c7a86a0bc404cbe54a7fc5c5d2e91c8f/.gitignore

Even though they are specified in `.gitignore`, files that remain without being deleted are visible. 
And it is determined that .gitignore needs to be updated to the latest.

For example,
- .idea : auto-generated folder & only redundant information for `IntelliJ` & `android-studio` IDE
- .DS_Store : auto-generated file through finder(Mac OS X)

Feel free to update `.gitignore` for android project & Remove all legacy stuffs

### References
- https://github.com/github/gitignore/blob/main/Android.gitignore
- https://www.toptal.com/developers/gitignore/api/androidstudio

**Comment by Kimhaedam** [comment]
I want to try it!

**Comment by Kimhaedam** [comment]
I'm asking if what I understand is correct👀

1. 'Delete the entire `.idea folder` and the `.DS_Store` within euphony and add newly deleted files to the `.gitignore` file'
2. 'Delete files that are currently written in `.gitignore` files but still exist in .idea folder within euphony'

I understood that it was **number 1** among them, is that right?
