### ISSUE TITLE
Euphony 빌드에 대한 detail한 가이드 작성

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#16]
@euphony-io/eutamin-c 팀에 배정되는 첫번째 이슈입니다.

초보 개발자 입장에서도 Guide를 보며 쉽게 빌드할 수 있게 친절한 설명이 필요할 것 같습니다.
스크린샷과 같은 그림 등이 들어가면 좋겠죠??

지금 버전인 0.7.1.6은 사실 라이브러리 빌드만 봤을때 엄청 간단하기 하지만
android-studio를 이용하지 않은 gradlew를 통한 빌드나 unit-test guide로의 확장이 가능할 것 같아요.

우선은 여기 issue를 통해서 팀원들과 커뮤니케이션을 하면서 전체 구성을 완성해보시구요.
내용도 어떻게 쓸지 각자 여기서 남겨가면서 작성해보면 좋겠습니다.
markdown을 연습한다는 생각으로 많이 많이 써주시면 좋을 것 같아요.

PR은 이번주 토요일 이후에 진행해보시도록 할게요 :)

**Comment by psh2849** [comment]
![1](https://user-images.githubusercontent.com/42669772/128962254-ba5ac425-2395-48e8-900e-c3e6a8cf1049.PNG)

Windows 운영체제 환경에서 Euphony 프로젝트를 gradlew로 빌드 했을 때 정상적으로 성공하였습니다.
추후에 매뉴얼을 작성할 때는 Windows / Linux, MacOS를 구분해서 작성해야 할 것 같아요!

우선, 참고했던 사이트 공유하겠습니다!
**gradlew 안드로이드 공식 문서**
https://developer.android.com/studio/build/building-cmdline?hl=ko

**Installing Gradle**
https://docs.gradle.org/current/userguide/installation.html#sec:installation_next_steps

**Gradle 파일 다운로드**
https://gradle.org/releases/

**Comment by Jsueeee** [comment]
![image](https://user-images.githubusercontent.com/66951780/128972979-4b28b754-2c04-4b15-b37d-9dfe1ec7ddbb.png)

git bash 사용했는데 Linux에 대한 가이드는 이 캡쳐 사용해도 될 것 같습니다!

**Comment by Jsueeee** [comment]
**초보 개발자를 위한 가이드** 이니 앞 부분에 이런 사소한 것도 넣으면 좋을 것 같습니다.

## 프로젝트 폴더로 이동

![image](https://user-images.githubusercontent.com/66951780/128973423-ae664855-0999-4e5c-8c98-3ce7cad4d3ca.png)

**Comment by psh2849** [comment]
> **초보 개발자를 위한 가이드** 이니 앞 부분에 이런 사소한 것도 넣으면 좋을 것 같습니다.
> 
> ## 프로젝트 폴더로 이동
> ![image](https://user-images.githubusercontent.com/66951780/128973423-ae664855-0999-4e5c-8c98-3ce7cad4d3ca.png)

좋은 것 같습니다! 저도 프로젝트 폴더 안에서 안해서 몇 번 Build Fail 떴었어요,,

**Comment by seoh02h** [comment]
# Euphony Build Guide

### Windows
```
git clone https://github.com/euphony-io/euphony.git
cd euphony/
gradlew
```

### Linux
```
git clone https://github.com/euphony-io/euphony.git
cd euphony/
./gradlew build
```
### Reference
* [gradlew 안드로이드 공식 문서](https://developer.android.com/studio/build/building-cmdline?hl=ko
)

* [Installing Gradle](https://docs.gradle.org/current/userguide/installation.html#sec:installation_next_steps
)

* [Gradle 파일 다운로드](https://gradle.org/releases/)

저도 windows 환경에서 git bash를 이용하여 성공하였습니다.
앞에 써주신 내용들 참고해서 일단 정리해보았습니다. 어떤 내용 더 추가하면 좋을지 계속 고민해볼게요 !!

**Comment by Jsueeee** [comment]
![image](https://user-images.githubusercontent.com/66951780/129007100-3754c100-a5d8-4063-b627-b263e4f44d1f.png)

@designe  멘토님! 유닛테스트 가이드에 대한 내용은 이런 식으로 기존 테스트 진행하는 방식에 대해 설명하면 될까요?

**Comment by seoh02h** [comment]
* Build > Select Build Variant
![image](https://user-images.githubusercontent.com/68395698/129009071-5202ed26-89fd-4a31-92c4-33ba5ce87936.png)
* Select the build variant that you want
![image](https://user-images.githubusercontent.com/68395698/129009271-b67cd6ae-d452-41fd-9bf3-dcdef359190a.png)
* Build > Make Module 'euphony.euphony'
![image](https://user-images.githubusercontent.com/68395698/129009491-15c897ec-29fb-4ec6-a7bd-7bd6532a9336.png)

안드로이드 스튜디오 내에서 빌드 방법을 정리해보았습니다!

**Comment by designe** [comment]
> ![image](https://user-images.githubusercontent.com/66951780/129007100-3754c100-a5d8-4063-b627-b263e4f44d1f.png)
> 
> @designe 멘토님! 유닛테스트 가이드에 대한 내용은 이런 식으로 기존 테스트 진행하는 방식에 대해 설명하면 될까요?

unit-test는 일단 이번주는 패스하고 나중에 알려드리고 진행하려고 했는데 ㅎㅎ
이미 발견해버리셨군요! 네네, 좋습니다 :)

**Comment by psh2849** [comment]
> 질문이 있습니다!
> windows환경에서 git bash를 이용하여 `./gradlew build ` 입력시 정상 빌드가 되었는데,
> cmd에서 `gradlew build` 입력 시 다음과 같은 에러가 발생합니다. 저와 같은 에러를 겪으신 분 있을까요?! 사진과 밑에 전체 에러도 첨부합니다 !
> ![image](https://user-images.githubusercontent.com/68395698/129010841-50c7870a-04f0-42d6-8c8f-07c9f5ed5bee.png)
> 
> 전체 에러

저도 동일한 에러가 발생하는데 혹시 해결하셨나요..?
![22](https://user-images.githubusercontent.com/42669772/129034179-9a2564d9-f4d6-4cd2-82a8-cd943d3a9983.PNG)
![33](https://user-images.githubusercontent.com/42669772/129034285-a6f2f7b1-82eb-4c54-a38c-d9df9c645cac.PNG)

해당 폴더 안에 있는 lint-results 파일들을 삭제하고, 다시 gradlew build를 했을 때 정상적으로 빌드가 됩니다.
근데 그 후에 다시 빌드 하게 되면 마찬가지로 또 에러가 발생하네요,,

**Comment by designe** [comment]
@seoh02h @psh2849 
해당 이슈에 대해서 상세한 로그 첨부 감사드립니다! :)
본 이슈는 운영체제의 gradle이 lint check 시 error로 판단하게 세팅이 되어 있어서 발생하는 문제로 보여요.

`gradlew build -x lint` 이 명령어로 빌드하면 lint 체크를 빌드할때 제외하기 때문에 해당 이슈가 발생하지 않을 것 같아요.
다만, lint 가 찾아내는 이슈는 warning 이라도 가능한 잡아주는 것이 코드를 안전하게 만들어주기 때문에
lint에 관한 문제는 0.8 버전 이후에 한번 @euphony-io/eutamin-c 팀에서 해결해보면 좋겠다는 생각이 듭니다! :)

**Comment by Jsueeee** [comment]
# Unit Test

## Run
![image](https://user-images.githubusercontent.com/66951780/129041141-9fc5a0f0-a991-47fe-8990-a55f221034fb.png)

The test file can be right-clicked and run using 'Run'.
테스트파일을 우클릭 후 'Run' 을 이용해 실행할 수 있습니다.

## Success
![image](https://user-images.githubusercontent.com/66951780/129039524-2d6488db-a71f-4da1-97d1-2cdbcd74df01.png)

Success if Expected and Actual have the same results.
Expected 와 Actual 의 결과가 같으면 성공입니다.

## Failure
![image](https://user-images.githubusercontent.com/66951780/129039632-b46ab05c-8eae-4262-b1be-bd3ac2e07a16.png)

```
Expected : hello
Actual : hell
```

**Tests failed** because the results of Expected and Actual are different.
Expected 와 Actual 의 결과가 다르기 때문에 Tests failed 의 결과가 나옵니다.

**Comment by seoh02h** [comment]
네, 감사합니다 !!


> @seoh02h @psh2849
> 해당 이슈에 대해서 상세한 로그 첨부 감사드립니다! :)
> 본 이슈는 운영체제의 gradle이 lint check 시 error로 판단하게 세팅이 되어 있어서 발생하는 문제로 보여요.
> 
> `gradlew build -x lint` 이 명령어로 빌드하면 lint 체크를 빌드할때 제외하기 때문에 해당 이슈가 발생하지 않을 것 같아요.
> 다만, lint 가 찾아내는 이슈는 warning 이라도 가능한 잡아주는 것이 코드를 안전하게 만들어주기 때문에
> lint에 관한 문제는 0.8 버전 이후에 한번 @euphony-io/eutamin-c 팀에서 해결해보면 좋겠다는 생각이 듭니다! :)

**Comment by sunnnl** [comment]
MacOS는 패키지 관리자 Homebrew를 통해서도 Gradle을 설치할 수 있어요 !
해당 내용도 추가되면 좋을 것 같습니다 :)
`brew install gradle`

**Comment by seoh02h** [comment]
## How to Build
### Clone this repository
```
git clone https://github.com/euphony-io/euphony.git
cd euphony/
```
### Build from the command line
```
./gradlew build
```
* ARR result files:  ./euphony/build/outputs/aar

## How to Test
### Test from the command line
```
./gradlew test 
```
* HTML test result files:  ./euphony/build/reports/tests
* XML test result files: ./euphony/build/test-results
