### ISSUE TITLE
Delete duplicate menus in issues tab

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#167]
This is one of the `good first issue`

![image](https://user-images.githubusercontent.com/1748714/180636327-c8fdac7b-b758-487c-a566-db671ab4545f.png)

As you can see, there are 2 links to open `blank issue`.

One is the `Don't see your issue? Open a blank issue.` in the lower left.
Another one is the `Custom issue template`.

How about deleting the `Custom issue template` menu? 
It is overlapping, but it also seems to go against unity.

**Comment by 9gl** [comment]
Hey @designe  , I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by designe** [comment]
Hey @9gl, I like your id. 😄 

As you can see, there are 2 linkes to `blank template`.
So, In this issue, what we want to do is to delete `/.github/ISSUE_TEMPLATE/custom.md`
https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/custom.md

**Comment by 9gl** [comment]
So this ```/.github/ISSUE_TEMPLATE/custom.md ```  is to be deleted?

**Comment by designe** [comment]
@9gl exactly, it is the one of the solution.

**Comment by 9gl** [comment]
So I can just delete and submit as a pull request?
