### ISSUE TITLE
[Sample App Proposal] Euphoever

### ISSUE THREAD

**Issue by yoouyoou** [euphony-io/euphony#177]
### What's your app name?

Account-Touch

### Main features

1. 계좌 등록
2. 계좌 송수신
3. 외부 앱 연동

### The features of the app are as follows:

![image](https://user-images.githubusercontent.com/81459048/181877206-52da2fb9-c90b-47f4-9046-4c0e63071130.png)
![image](https://user-images.githubusercontent.com/81459048/181877215-2bc22a59-9e94-4c96-badb-c26e79a57917.png)

### Who made it?

Co-authored-by: @yoouyoou @HongEunbeen @kldaji 

### Submit your repository link!

https://github.com/euphony-io/account-touch.git

**Comment by yeonns** [comment]
@euphony-io/euphoever Hi :) Thank you for sample app proposal!
Would you make PR with updating ```README.md``` like [this link](https://github.com/euphony-io/euphony/pull/36)?
