### ISSUE TITLE
[Sample App Proposal] wave-show-card

### ISSUE THREAD

**Issue by DahyeonWoo** [euphony-io/euphony#178]
### What's your app name?

wave-show-card

### Main features

(Visually Impaired)
* When a visually impaired person clicks the web show card, the show card transmits sound waves.
* When a visually impaired person brings the app near the show card, the app receives the sound waves of the show card, interprets the content, and plays it as a sound.

(Clerk)
* The clerk can save and modify the contents of the show card using a web socket.

### The features of the app are as follows:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/44018024/181766356-6db799c5-ef46-42b6-9d17-608b2a45a38f.gif)

1. 점원이 웹 쇼카드에 상품명(cap), 가격정보(1)를 입력한다.
2. 웹 쇼카드에서 음파신호를 송신한다.
3. 앱에서 음파신호를 수신 후 음성으로 출력한다. 

### Who made it?

Co-authored-by: @sunyeongan @Han-D-Peter @defwdahyun0

### Submit your repository link!

https://github.com/euphony-io/wave-show-card

**Comment by yeonns** [comment]
@euphony-io/euterpe Hi :) Thank you for sample app proposal!
Would you make PR with updating ```README.md``` like [this link](https://github.com/euphony-io/euphony/pull/36)?
