### ISSUE TITLE
[Sample App Proposal] <order-with>

### ISSUE THREAD

**Issue by phj0407** [euphony-io/euphony#179]
### What's your app name?

Order-With

### Main features

- 고객에게 메뉴 리스트 전송
- 고객이 주문 전송 시 가게 기기에 알림

추후 업데이트
- 주문 요청과 메뉴 요청을 주파수를 이용해서 구분

### The features of the app are as follows:

<img src ="https://user-images.githubusercontent.com/89901283/181918959-0a386abf-2d84-4ed8-a941-9c01e88824d9.jpg" width = "380"/>

[ MAIN ] 
<img src ="https://user-images.githubusercontent.com/89901283/181918961-9d49a827-a127-42a5-8062-cbc0711e6655.jpg" width = "380"/>
[ Receive Menu ]
<img src ="https://user-images.githubusercontent.com/89901283/181918964-bff56f94-d98d-404d-9507-dbbc4da29a8b.jpg" width = "380"/>
<img src ="https://user-images.githubusercontent.com/89901283/181918965-5a069884-08c2-47c1-96f2-ab780791a600.jpg" width = "380"/>
[ Receive Order ] 

### Who made it?

Co-authored-by: @phj0407
Co-authored-by: @SeonJK 
Co-authored-by: @serim53 

### Submit your repository link!

https://github.com/euphony-io/order-with

**Comment by yeonns** [comment]
@euphony-io/eunicorn Hi :) Thank you for sample app proposal!
Would you make PR with updating ```README.md``` like [this link](https://github.com/euphony-io/euphony/pull/36)?
