### ISSUE TITLE
Suggested: Advanced Logging Idea

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony#205]
### Discussed in https://github.com/orgs/euphony-io/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **zion830** August 25, 2022</sup>
## Summary
When we use Euphony without RECORD_AUDIO permission, the process is killed with `IllegalStateException`

**Full error message**
```
java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord
```
When I first saw this, it's hard to know at once that it is caused by a permission.
Even though it's already written in README, it's a pretty common mistake.
So I suggest this idea!

## How to improve
1. If listen() is called without RECORD_AUDIO permission, listen() function ends immediately to prevent death of the app
2. Print a log requiring the permission with `Log.e`
 
**Example**
```
Before calling listen(), you should acquire RECORD_AUDIO permission.
```

</div>

**Comment by zion830** [comment]
Could you assign this issue to @sunyeongan together?

**Comment by sunyeongan** [comment]
@zion830 Okay!! goooood! I will find related API .
