### ISSUE TITLE
Suggested: Apply Singleton pattern to EuTxManager

### ISSUE THREAD

**Issue by yeonns** [euphony-io/euphony#260]
### Discussed in https://github.com/orgs/euphony-io/discussions/259

<div type='discussions-op-text'>

<sup>Originally posted by **SeonJK** September 18, 2022</sup>
# AS-IS
While using EuTxManager with multiple instances, they cause wrong  execution.
For example, adding multiple EuTxManager due to add multiple EuPI, app cannot easily manage EuPI.

# TO-DO
By applying Singleton pattern, code prevents from several issues.

![image](https://user-images.githubusercontent.com/37062147/190893228-ba85b2bd-4f84-46e9-b720-9bca4ca1cbdc.png)

<br/>

I suggest singleton pattern by Bill Pugh solution. It makes sure Thread-safe.

Applying singleton pattern by @Volatile and @Synchronized causes performance decreasement.
However by Bill Pugh solution, EuTxManager class makes singleton through Holder class. Holder class makes sure to load once.

References:
- https://stackoverflow.com/questions/50771372/bill-pugh-singleton-why-thread-safe
- https://itzone.com.vn/en/article/bill-pugh-singleton-in-java-incredibly-simple/
- https://medium.com/swlh/singleton-design-pattern-with-kotlin-2e6c8d42fc11#:~:text=Singleton.INSTANCE.doSomeThin()-,we,-can%20create%20a</div>

**Comment by SeonJK** [comment]
Hi, @designe @yeonns 
I have a question about downloading EuTxManager.kt.

EuTxManager.kt is been merged to `master`, so I tried to `git fetch` and `git pull` command for download in my local repo. But it's not worked!

I think EuTxManager.kt is behind `release 0.8.1.2`, but i want to use it for resolving this issue.

How can I download EuTxManager.kt?
