### ISSUE TITLE
[Sample App Proposal] wave-pdf

### ISSUE THREAD

**Issue by phj0407** [euphony-io/euphony#269]
### What's your app name?

wave-pdf

### Main features

- Show pdf pages
- Control pdf page move
- We will update : ppt-version

### The features of the app are as follows:

Sample App for using Euphony library - EuPI mode. You can show pdf file to viewer, and control it by controller.

## Controller
<table>
  <tr>
<td><img src="https://user-images.githubusercontent.com/89901283/191147390-d10fc7a8-f9b3-4ae8-90d6-5fba5024a2d5.png" height = "400px" />
<td><img src="https://user-images.githubusercontent.com/89901283/191147398-dc184dc9-5302-4f76-8165-c6fdcc4fa180.png" height = "400px" />
<td><img src="https://user-images.githubusercontent.com/89901283/191147408-7a395362-dc47-4581-9b3f-5b9c2628ab90.png" height = "400px" />
<tr>
</table>  

In controller, you just move to control page and click button. Then, device will generate sound wave.  

<br/>
<br/>

### 1. Permmisions allow : Record Audio & Access Stroage  
<table>
  <tr>
<td><img src="https://user-images.githubusercontent.com/89901283/191147656-c901aad4-df92-41fd-95e8-94fd4f4710ca.png" height = "400px" />
<td><img src="https://user-images.githubusercontent.com/89901283/191147647-4439059d-a682-486a-a11d-acead50f453f.png" height = "400px" />
<tr>
</table>  
<br/>
    
### 2. Select PDF file you want to show.  
<table>
  <tr>
<td><img src="https://user-images.githubusercontent.com/89901283/191147894-54a9a076-5142-411c-922b-b9928dece708.png" height = "400px" />
<td><img src="https://user-images.githubusercontent.com/89901283/191147901-c59c22cf-c6de-4ef6-a141-746f245816d9.png" height = "400px" />
<tr>
</table>  
<br/>
    
### 3. If you success to load PDF, device will listen automatically and move page by controller's signal.  
<img src="https://user-images.githubusercontent.com/89901283/191148029-efb3d8e4-623a-4108-894d-2925bb6a9f61.png" height = "400px" />

### Test

![KakaoTalk_20220920_130150192 (online-video-cutter com) (1) (3) (1)](https://user-images.githubusercontent.com/89901283/191165993-54aeac22-b83b-4945-a9c3-c95a36241833.gif)

### Who made it?

Co-authored-by: @phj0407  https://github.com/phj0407
Co-authored-by: @nodobi  https://github.com/nodobi

### Submit your repository link!

https://github.com/euphony-io/wave-ppt

**Comment by designe** [comment]
@phj0407 is it not yours?
https://github.com/euphony-io/euphony/issues/220

**Comment by phj0407** [comment]
Oh, yes, it's mine. I forgot I already upload issue 🤦‍♀️ The, I just update README.md and open pr?

**Comment by designe** [comment]
@phj0407 yeah right!
